#!/usr/bin/env node

var fs = require('fs');
var readline = require("readline");

var action = (process.argv[2]) ? process.argv[2] : null;

if(action == 'create') {

    var defaultPermissions = '0755';

    var rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });

    rl.question("Default Namespace: \n", function (input) {

        var ns = input.split(":");
        var vendorName = ns[0];
        var moduleName = ns[1];

        // Setup app/config/altair.json
        var filePath    = "/app/config/altair.json";
        var altairJson  = "{\n\t\"name\" : \"altair-boilerplate\",\n\t\"description\" : \"Boilerplate Altair Config\",\n\t\"version\" : \"0.0.0.1\",\n\t\"dependencies\" : {\n\t\t\"altair.io\" : \">=0.0.9\"\n\t}\n}";
        var packageJson = "{\n\t\"name\" : \"altair-project\", \n\t\"description\" : \"Altair Boilerplate\",\n\t\"version\" : \"0.0.1\",\n\t\"altair-dependencies\" : {\n\t}\n}";

        fs.writeFile('package.json', packageJson, function (err) {
            if (err) throw err;
            console.log('CREATED : package.json');
        });

        fs.mkdirSync('app', defaultPermissions);
        fs.mkdirSync('app/config', defaultPermissions);
        fs.writeFile('app/config/altair.json', altairJson, function (err) {
            if (err) throw err;
            console.log('CREATED : app/config/altair.json');
        });

        fs.mkdirSync('app/vendor', defaultPermissions);
        fs.mkdirSync('app/vendor/' + vendorName, defaultPermissions);
        fs.mkdirSync('app/vendor/' + vendorName + '/modules', defaultPermissions);
        fs.mkdirSync('app/vendor/' + vendorName + '/modules/' + moduleName, defaultPermissions);
        fs.writeFile('app/vendor/' + vendorName + '/modules/' + moduleName + '/package.json', packageJson, function (err) {
            if (err) throw err;
            console.log('CREATED : app/vendor/' + vendorName + '/modules/' + moduleName + 'package.json');
        });
        rl.close();
    });
}
else
{
    console.log('No Action Specified');
}

